spring:
  application:
    name: SpringAI-Demo
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4o-mini
    anthropic:
      api-key: ${ANTHROPIC_KEY}
      chat:
        options:
          model: claude-haiku-4-5

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
